### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by randx** [hyb1996/Auto.js#233]
试用了一段时间, 反馈一下碰到的问题. 

*)app自带bug report功能用不了, 递交不到github.
*)app里编辑器在转屏时,会丢失当前编辑内容.  需要在旋转屏幕前手动存档. 

*)悬浮窗UI工具看到的控件, 在脚本里用选择器搜索,经常找不到. , 经过尝试,发现两个trick.可以帮助定位控件.一是用id严格匹配筛选条件,即使控件有唯一idName. 用 id(packageName:id/idName).findOne 替代 id(idName).findOne, 二是用loop+.find()等寻, 代替 .findOne(). (脚本和UI工具搜索算法不一样? 能提高脚本中的控件搜索效率? )

*)用Tasker设置定时任务, 调用autojs脚本. 亮屏状态下脚本运行没有问题. 但如果执行时手机处在屏保状态. 脚本执行完launchApp和某个点击控件动作后就停止. 屏幕解锁后继续运行时出错. 怎么在锁屏状态下运行完程序?

*)图形函数RequestScreenCapture() crash. (ROM LineageOS14.1,android7.1.2). 问题在screencapture.java里 mImageReader = ImageReader.newInstance(screenWidth, screenHeight, PixelFormat.RGBA_8888, 1);  virtualdisplay 生成pixel.format是BGRA_8888, code 0x5, ImageReader不支持BGRA格式. 设置成RGBA_8888, 0x1 读取出错. 查了一下, 这个问题可能和rom有关,(CyanogenMod 上常见). 

autojs能添加对BGRA_8888图片格式支持?   

Version: 163
Android: 25
java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.
	at android.media.ImageReader.nativeImageSetup(Native Method)
	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:340)
	at android.media.ImageReader.acquireNextImage(ImageReader.java:394)
	at android.media.ImageReader.acquireLatestImage(ImageReader.java:287)
	at com.stardust.autojs.runtime.api.image.ScreenCapturer$2.onImageAvailable(ScreenCapturer.java:93)
	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:687)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at com.stardust.autojs.runtime.api.Loopers$2.run(Loopers.java:57)
	at java.lang.Thread.run(Thread.java:761)
	at com.stardust.lang.ThreadCompat.run(ThreadCompat.java:61)

*)图形处理capturescreen()截屏成功率低.(flymeOS android 6) 用50ms的采样率截屏,延时能
有1秒.如何能提高截屏成功率? (帮助文档里提到该函数耗时在1ms以内, 实在是不可及.)  

Log: 10:49:49.578/D: capture rate: 50(ms)
Log: 10:49:49.622/D: sample 0: timestamp=1504406989621; dt = 0
Log: 10:49:49.680/D: sample 1: timestamp=1504406989679; dt = 58
Log: 10:49:49.733/D: sample 2: timestamp=1504406989733; dt = 54
Log: 10:49:50.358/D: sample 3: timestamp=1504406990358; dt = 625
Log: 10:49:51.355/D: sample 4: timestamp=1504406991354; dt = 996
Log: 10:49:51.639/D: sample 5: timestamp=1504406991639; dt = 285
Log: 10:49:51.692/D: sample 6: timestamp=1504406991692; dt = 53
Log: 10:49:52.351/D: sample 7: timestamp=1504406992350; dt = 658
Log: 10:49:53.348/D: sample 8: timestamp=1504406993347; dt = 997
Log: 10:49:54.343/D: sample 9: timestamp=1504406994342; dt = 995
Log: 10:49:55.346/D: sample 10: timestamp=1504406995346; dt = 1004
 
*)capturescreen()返回的image.timestamp是不是截屏时间戳? (以nano sec为单位?) 
记录截屏时间间隔dt, 为什么和用系统时间Date().getTime()返回的偏差很大 ? (0~70ms )

Log: 00:32:23.806/D: sample 6 : img.timestamp=140716243900132; dt = 174311041
Log: 00:32:23.838/D: system : t=1504369943772; dt = 173
Log: 00:32:23.974/D: sample 7 : img.timestamp=140716348173424; dt = 104273292
Log: 00:32:24.001/D: system : t=1504369943943; dt = 171
Log: 00:32:24.753/D: sample 8 : img.timestamp=140717190255216; dt = 842081792
Log: 00:32:24.784/D: system : t=1504369944717; dt = 774

*) findColor()在区域查色时,如果用threshold开关, 参数格式用数值0xRRGGBB, 会返回错误结果.即总能
返回非空point object. 如果用单数字格式thresold: 123 则没有问题. 
可以在示例脚本"区域找色2"里测试. findColor()添加threshold: 0x020202, 再改目标色,会发现总能找到.但颜色不匹配.  (这个bug用了较长时间才发现) 

var point = findColor(image,testColor,{
	 	region: testRect,
	  	algorithm: "diff",
	  	threshold: 0x020202,
	  	threads:8
	  })

*)使用图形函数功能经常闪退 . 

Version: 163
Android: 22
java.lang.IllegalStateException: buffer was freed
	at java.nio.DirectByteBuffer.checkNotFreed(DirectByteBuffer.java:557)
	at java.nio.DirectByteBuffer.checkIsAccessible(DirectByteBuffer.java:549)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:162)
	at com.stardust.autojs.runtime.api.image.ColorIterator$SequentialIterator.nextColor(ColorIterator.java:111)
	at com.stardust.autojs.runtime.api.image.ColorFinder$FindColorRunnable.run(ColorFinder.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

附带问题:  
*)对没有accessibility service接口的UI控件,autojs有可能扩展支持? (比如cocos-2d js的UI文本控件,能从
android.view.View根控件访问到么? ) 
*)会不会支持更多图形处理功能和OCR? 

期待尽快出新版 (all above is on 2.0.16 beta2.1)

**Comment by hyb1996** [comment]
* app自带bug report功能用不了, 递交不到github
会不会是网络问题？github可能在某些地方被墙

**Comment by hyb1996** [comment]
* app里编辑器在转屏时,会丢失当前编辑内容. 需要在旋转屏幕前手动存档:
Bug

**Comment by hyb1996** [comment]
* 悬浮窗UI工具看到的控件, 在脚本里用选择器搜索,经常找不到. , 经过尝试,发现两个trick.可以帮助定位控件.一是用id严格匹配筛选条件,即使控件有唯一idName. 用 id(packageName:id/idName).findOne 替代 id(idName).findOne, 二是用loop+.find()等寻, 代替 .findOne(). (脚本和UI工具搜索算法不一样? 能提高脚本中的控件搜索效率? )
id问题应该是软件实时获取当前包名的算法有问题
可以尝试开启稳定模式

**Comment by hyb1996** [comment]
* 图形处理capturescreen()截屏成功率低.(flymeOS android 6) 用50ms的采样率截屏,延时能
有1秒.如何能提高截屏成功率? (帮助文档里提到该函数耗时在1ms以内, 实在是不可及.)

第一次截屏时间会久一点。另外只在小米6上测试过，我试试在其他机型上测试

**Comment by hyb1996** [comment]
* capturescreen()返回的image.timestamp是不是截屏时间戳? (以nano sec为单位?)
记录截屏时间间隔dt, 为什么和用系统时间Date().getTime()返回的偏差很大 ? (0~70ms )

这个我需要去确认一下

**Comment by hyb1996** [comment]
* findColor()在区域查色时,如果用threshold开关, 参数格式用数值0xRRGGBB, 会返回错误结果.即总能
返回非空point object. 如果用单数字格式thresold: 123 则没有问题.
可以在示例脚本"区域找色2"里测试. findColor()添加threshold: 0x020202, 再改目标色,会发现总能找到.但颜色不匹配. (这个bug用了较长时间才发现)

threshold函数只能是0~255的数字。不能是0xRRGGBB。这个不像按键精灵。事实上你会发现按键精灵RRGGBB的差值我们一般都是用同一个数字，比如0x232323，很少情况会写0x123456之类的。因此这种设计我觉得更加方便

**Comment by hyb1996** [comment]
* 使用图形函数功能经常闪退 .

Version: 163
Android: 22
java.lang.IllegalStateException: buffer was freed
at java.nio.DirectByteBuffer.checkNotFreed(DirectByteBuffer.java:557)
at java.nio.DirectByteBuffer.checkIsAccessible(DirectByteBuffer.java:549)
at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:162)
at com.stardust.autojs.runtime.api.image.ColorIterator$SequentialIterator.nextColor(ColorIterator.java:111)
at com.stardust.autojs.runtime.api.image.ColorFinder$FindColorRunnable.run(ColorFinder.java:217)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

Bug

**Comment by hyb1996** [comment]
* 对没有accessibility service接口的UI控件,autojs有可能扩展支持? (比如cocos-2d js的UI文本控件,能从
android.view.View根控件访问到么? 
这个暂时考虑支持，并且也没有确认过实现的可能性
* 会不会支持更多图形处理功能和OCR?
会加入找图功能。OCR只能支持在线API否则软件体积会很大

**Comment by hyb1996** [comment]
* 用Tasker设置定时任务, 调用autojs脚本. 亮屏状态下脚本运行没有问题. 但如果执行时手机处在屏保状态. 脚本执行完launchApp和某个点击控件动作后就停止. 屏幕解锁后继续运行时出错. 怎么在锁屏状态下运行完程序?
具体是怎样的代码？我尝试锁屏状态（屏幕亮着）下运行网易云音乐点赞脚本可行。

**Comment by qizhihere** [comment]
遇到同样的无法获取id的问题，尝试开启稳定模式也是一样。直接用packageName:id/xxx的格式也不行。
App: 钉钉4.2.8
界面: 工作-考勤打卡-右上角选择日期-月历界面
无法根据id获取月历控件: day_picker_view_pager

**Comment by qizhihere** [comment]
遇到同样的id无法查找到控件的问题，尝试开启稳定模式也是一样。直接用packageName:id/xxx的格式也不行。
App: 钉钉4.2.8
界面: 工作-考勤打卡-右上角选择日期-月历界面
无法根据id获取月历控件: day_picker_view_pager

**Comment by hyb1996** [comment]
鉴于这个issue已经很久了
目前遗留的问题已经提了新issue，因此关闭这个issue
