### ISSUE TITLE
sublime test plugin 异常

### ISSUE THREAD

**Issue by 1178615156** [hyb1996/Auto.js#249]
在手机上脚本还在正常运行,但是电脑上抛出如下异常,并`disconnected`
```<class 'Exception'> : Extra data: line 1 column 57 - line 2 column 1 (char 56 - 134)
Traceback (most recent call last):
  File "autojs in C:\Users\yujieshui\AppData\Roaming\Sublime Text 3\Installed Packages\autojs.sublime-package", line 45, in listen
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 354, in decode
ValueError: Extra data: line 1 column 57 - line 2 column 1 (char 56 - 134)
```

**Comment by asiontang** [comment]
[修复了Extra data: line 1 column 57 - line 2 column 1 · asiontang/AutoJs-Sublime-Plugin@f393fff](https://github.com/asiontang/AutoJs-Sublime-Plugin/commit/f393ffff2bc198db63e7078191bdd325f29e9e80)
