### ISSUE TITLE
无法正确判断悬浮窗是否开启

### ISSUE THREAD

**Issue by MikaGuraN** [hyb1996/Auto.js#272]
分两个情况

第一个比较正常，FloatService被停止
应用仍然显示悬浮窗已经开启，点关闭，报错

另一个就比较奇怪了
在我4.4的手机里，明明悬浮窗没有开着，他显示开着，我点关，他会提示

    <string name="text_click_too_frequently">您的操作太快啦ヽ(#`Д´)ﾉ</string>

(从源码里搜出来的，不过实在找不到哪里有问题)

然后再点关闭再开启就可以重新打开了

建议给服务设置一个停止事件.....

**Comment by MikaGuraN** [comment]
贴一下Auto.js报错的内容(好像提交到Github没用啊)

[213]java.lang.IllegalArgumentException: View=com.stardust.floatingcircularactionmenu.CircularActionMenu{99f870f G.E...... ......ID 0,0-732,726} not attached to window manager

java.lang.IllegalArgumentException: View=com.stardust.floatingcircularactionmenu.CircularActionMenu{99f870f G.E...... ......ID 0,0-732,726} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:479)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:388)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:121)
	at com.stardust.floatingcircularactionmenu.CircularActionMenuFloatingWindow.close(CircularActionMenuFloatingWindow.java:156)
	at com.stardust.scriptdroid.ui.floating.CircularMenu.close(CircularMenu.java:271)
	at com.stardust.scriptdroid.ui.floating.FloatyWindowManger.hideCircularMenu(FloatyWindowManger.java:79)
	at com.stardust.scriptdroid.ui.main.drawer.DrawerFragment.showOrDismissFloatingWindow(DrawerFragment.java:165)
	at com.stardust.scriptdroid.ui.main.drawer.DrawerFragment_$3.onClick(DrawerFragment_.java:118)
	at com.stardust.scriptdroid.ui.main.drawer.DrawerMenuItem.onClick(DrawerMenuItem.java:112)
	at com.stardust.scriptdroid.ui.main.drawer.DrawerMenuItem.access$000(DrawerMenuItem.java:28)
	at com.stardust.scriptdroid.ui.main.drawer.DrawerMenuItem$1.onCheckedChanged(DrawerMenuItem.java:93)
	at com.stardust.widget.SwitchCompat$1.onCheckedChanged(SwitchCompat.java:36)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:156)
	at android.support.v7.widget.SwitchCompat.setChecked(SwitchCompat.java:1062)
	at com.stardust.widget.PrefSwitch.setChecked(PrefSwitch.java:83)
	at com.stardust.widget.PrefSwitch.setChecked(PrefSwitch.java:78)
	at android.support.v7.widget.SwitchCompat.toggle(SwitchCompat.java:1057)
	at android.widget.CompoundButton.performClick(CompoundButton.java:120)
	at android.view.View$PerformClick.run(View.java:22462)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6379)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by hyb1996** [comment]
你试试最新版是否还有这个问题 https://github.com/hyb1996/Auto.js/releases/tag/3.0.0Alpha40
你用的版本是很久以前的了

**Comment by MikaGuraN** [comment]
@hyb1996 现在应该没有错了....
