### ISSUE TITLE
android4.4界面分析导致的报错

### ISSUE THREAD

**Issue by MikaGuraN** [hyb1996/Auto.js#273]
我这里android7.1可以正常使用
但是在旧手机会报错(4.4)

**Comment by MikaGuraN** [comment]
贴一下报错内容

[213]java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams

java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
	at android.widget.ListView.setupChild(ListView.java:1826)
	at android.widget.ListView.makeAndAddView(ListView.java:1793)
	at android.widget.ListView.fillDown(ListView.java:691)
	at android.widget.ListView.fillFromTop(ListView.java:752)
	at android.widget.ListView.layoutChildren(ListView.java:1616)
	at android.widget.AbsListView.onLayout(AbsListView.java:2111)
	at android.view.View.layout(View.java:14834)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14834)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1988)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1001)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5623)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5241)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by hyb1996** [comment]
最新版应该是修复了的 https://github.com/hyb1996/Auto.js/releases/tag/3.0.0Alpha40
