### ISSUE TITLE
Auto.js长期执行脚本的疑问

### ISSUE THREAD

**Issue by spliu78** [hyb1996/Auto.js#337]
A脚本定时重启B脚本，B脚本负责主要逻辑，一小时一次，基本能稳定运行一周左右，之后Auto就无反应了，点开APP的日志界面是空白页无日志，且手机返回按钮不可使用，需重启，这是为何？
手机是小米MAX2，已root

**Comment by hyb1996** [comment]
目前Auto.js还没有进行长时间运行的稳定性试验
如果手上有工具的话 可以抓出无反应后的Android Logcat日志反馈给我

**Comment by spliu78** [comment]
嗯，在抓logcat了
现在想采取一个backup方案，将手机连上电脑使用adb去执行A脚本，定时杀死auto.js
但我怎样才能用adb去调起auto执行A脚本呢？是我没找对Activitty么？
以下方法报错：
```
$ adb -s 79BQADSE59LNG shell am start -n com.stardust.scriptdroid/.ui.main.MainActivity_ -d file:///sdcard/脚本/A.js
Starting: Intent { dat=file:///sdcard/脚本/A.js cmp=com.stardust.scriptdroid/.ui.main.MainActivity_ }
java.lang.SecurityException: Permission Denial: starting Intent { dat=file:///sdcard/脚本/A.js flg=0x10000000 cmp=com.stardust.scriptdroid/.ui.main.MainActivity_ } from null (pid=20117, uid=2000) not exported from uid 10104
        at android.os.Parcel.readException(Parcel.java:1683)
        at android.os.Parcel.readException(Parcel.java:1636)
        at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:3409)
        at com.android.commands.am.Am.runStart(Am.java:635)
        at com.android.commands.am.Am.onRun(Am.java:388)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:121)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:308)
```
