### ISSUE TITLE
每次后台运行时都会崩溃

### ISSUE THREAD

**Issue by shawnming** [hyb1996/Auto.js#375]
Version: 256
Android: 27
java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.readException(Parcel.java:2011)
	at android.os.Parcel.readException(Parcel.java:1951)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.findAccessibilityNodeInfoByAccessibilityId(IAccessibilityServiceConnection.java:447)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:290)
	at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:162)
	at android.accessibilityservice.AccessibilityService.getRootInActiveWindow(AccessibilityService.java:569)
	at com.stardust.view.accessibility.AccessibilityService.onAccessibilityEvent(AccessibilityService.java:63)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1524)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1710)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by hyb1996** [comment]
已修复

**Comment by TheMelody** [comment]
> 已修复

怎么修复的？
