### ISSUE TITLE
需要什么服务和依赖吗？我在安卓虚拟机上面打开会crash

### ISSUE THREAD

**Issue by xiaobebe** [hyb1996/Auto.js#380]
![image](https://user-images.githubusercontent.com/19386356/46566888-bb830b80-c959-11e8-91ef-83a09daeaff9.png)

安卓版本 7.1.2

autojs版本4.0.2Alpha9

**Comment by hyb1996** [comment]
使用arm的模拟器试试

**Comment by xiaobebe** [comment]
最终解决了。不过希望作者能在文档中也说明一下。需要有ARM Native的支持。

虚拟机中需要安装 ARM Translation 

https://pan.baidu.com/s/1kUAftyR 

参考博客：https://blog.csdn.net/u012399175/article/details/54020032

**Comment by xiaobebe** [comment]
![image](https://user-images.githubusercontent.com/19386356/46572439-367b0f00-c9b8-11e8-9fd5-c93e5baa1669.png)

**Comment by hyb1996** [comment]
ARM Translation对与高版本的genymotion模拟器没有用

**Comment by xiaobebe** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.autojs.autojs, PID: 2330
    java.lang.RuntimeException: Unable to create application org.autojs.autojs.App: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:765)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
        at android.app.Dialog.show(Dialog.java:330)
        at org.opencv.android.BaseLoaderCallback.onPackageInstall(BaseLoaderCallback.java:110)
        at org.opencv.android.AsyncServiceHelper.InstallService(AsyncServiceHelper.java:117)
        at org.opencv.android.AsyncServiceHelper.initOpenCV(AsyncServiceHelper.java:33)
        at org.opencv.android.OpenCVLoader.initAsync(OpenCVLoader.java:107)
        at com.stardust.autojs.AutoJs.init(AutoJs.java:78)
        at com.stardust.autojs.AutoJs.<init>(AutoJs.java:68)
        at org.autojs.autojs.autojs.AutoJs.<init>(AutoJs.java:0)
        at org.autojs.autojs.autojs.AutoJs.initInstance(AutoJs.java:38)
        at org.autojs.autojs.App.init(App.java:79)
        at org.autojs.autojs.App.onCreate(App.java:55)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 

```

**Comment by xiaobebe** [comment]
![image](https://user-images.githubusercontent.com/19386356/46573173-c83c4980-c9c3-11e8-9b8d-9beef1ca5bf6.png)
是因为OpenCV没有的原因么

**Comment by hyb1996** [comment]
这个是opencv初始化失败或者正在初始化（仍然是动态链接库的abi问题），opencv尝试弹出一个对话框显示信息，但是这时的context是application，因此出现这个错误
