### ISSUE TITLE
控件生成代码崩溃

### ISSUE THREAD

**Issue by Nick-Hopps** [hyb1996/Auto.js#386]
Version: 249
Android: 26
java.lang.NullPointerException: Attempt to read from field 'int com.stardust.view.accessibility.NodeInfo.depth' on a null object reference
	at com.stardust.autojs.codegeneration.ReadOnlyUiObject.<init>(ReadOnlyUiObject.java:20)
	at com.stardust.autojs.codegeneration.CodeGenerator.<init>(CodeGenerator.java:29)
	at com.stardust.scriptdroid.ui.codegeneration.CodeGenerateDialog.generateCode(CodeGenerateDialog.java:92)
	at com.stardust.scriptdroid.ui.codegeneration.CodeGenerateDialog.generateCodeAndShow(CodeGenerateDialog.java:77)
	at com.stardust.scriptdroid.ui.codegeneration.CodeGenerateDialog.lambda$new$0$CodeGenerateDialog(CodeGenerateDialog.java:72)
	at com.stardust.scriptdroid.ui.codegeneration.CodeGenerateDialog$$Lambda$0.onClick(Unknown Source:2)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:361)
	at android.view.View.performClick(View.java:6291)
	at android.view.View$PerformClick.run(View.java:24931)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by hyb1996** [comment]
使用 https://github.com/hyb1996/Auto.js/releases/tag/4.0.4Alpha6
