### ISSUE TITLE
在使用nova时授予无障碍软件直接崩溃

### ISSUE THREAD

**Issue by storytellerF** [hyb1996/Auto.js#461]
再打开nova时，如果已经授权autojs无障碍，直接崩溃，或者打开nova,给autojs无障碍，然后退出到桌面。
手机是小米8。
这个问题不只重现，是次次中
Version: 256
Android: 28
java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createException(Parcel.java:1956)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.findAccessibilityNodeInfoByAccessibilityId(IAccessibilityServiceConnection.java:451)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:343)
	at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:207)
	at android.accessibilityservice.AccessibilityService.getRootInActiveWindow(AccessibilityService.java:583)
	at com.stardust.view.accessibility.AccessibilityService.onAccessibilityEvent(AccessibilityService.java:63)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1538)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1724)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl$AppWidgetManagerLocal.getHostedWidgetPackages(AppWidgetServiceImpl.java:4812)
	at com.android.server.accessibility.AccessibilityManagerService$SecurityPolicy.computeValidReportedPackages(AccessibilityManagerService.java:3060)
	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.findAccessibilityNodeInfoByAccessibilityId(AbstractAccessibilityServiceConnection.java:583)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub.onTransact(IAccessibilityServiceConnection.java:87)
	at android.os.Binder.execTransact(Binder.java:733)

**Comment by StorytellerF** [comment]
nova launch是在google play下载的免费版的

**Comment by TheMelody** [comment]
> 再打开nova时，如果已经授权autojs无障碍，直接崩溃，或者打开nova,给autojs无障碍，然后退出到桌面。
> 手机是小米8。
> 这个问题不只重现，是次次中
> Version: 256
> Android: 28
> java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
> at android.os.Parcel.createException(Parcel.java:1956)
> at android.os.Parcel.readException(Parcel.java:1918)
> at android.os.Parcel.readException(Parcel.java:1868)
> at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.findAccessibilityNodeInfoByAccessibilityId(IAccessibilityServiceConnection.java:451)
> at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:343)
> at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:207)
> at android.accessibilityservice.AccessibilityService.getRootInActiveWindow(AccessibilityService.java:583)
> at com.stardust.view.accessibility.AccessibilityService.onAccessibilityEvent(AccessibilityService.java:63)
> at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1538)
> at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1724)
> at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:201)
> at android.app.ActivityThread.main(ActivityThread.java:6806)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> Caused by: android.os.RemoteException: Remote stack trace:
> at com.android.server.appwidget.AppWidgetServiceImpl$AppWidgetManagerLocal.getHostedWidgetPackages(AppWidgetServiceImpl.java:4812)
> at com.android.server.accessibility.AccessibilityManagerService$SecurityPolicy.computeValidReportedPackages(AccessibilityManagerService.java:3060)
> at com.android.server.accessibility.AbstractAccessibilityServiceConnection.findAccessibilityNodeInfoByAccessibilityId(AbstractAccessibilityServiceConnection.java:583)
> at android.accessibilityservice.IAccessibilityServiceConnection$Stub.onTransact(IAccessibilityServiceConnection.java:87)
> at android.os.Binder.execTransact(Binder.java:733)

你是在桌面安装了什么其他小部件了吗

**Comment by TheMelody** [comment]
怎么解决的？没看到，就关闭问题了？

**Comment by hyb1996** [comment]
try catch解决 @TheMelody
