### ISSUE TITLE
悬浮窗里的控件无法绑定longClick事件

### ISSUE THREAD

**Issue by smile365** [hyb1996/Auto.js#497]
Auto.js 4.0.1 Beta  
手机：小米8   
代码如下：  
```javascript
var window = floaty.window(
    <frame >
        <text id="text" textSize="16sp" textColor="#f44336"/>
    </frame>
);
window.exitOnClose()
window.setPosition(700, 700);
ui.run(function(){
    window.text.setText("长按这个文字试试");
});

window.text.longClick(()=>{
    window.setAdjustEnabled(!window.isAdjustEnabled());
});
```

错误信息   
```
Version: 404
Android: 28
org.mozilla.javascript.EvaluatorException: Cannot convert undefined to boolean
 at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
 at org.mozilla.javascript.Context.reportRuntimeError(Context.java:980)
 at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1035)
 at org.mozilla.javascript.Context.reportRuntimeError2(Context.java:1005)
 at org.mozilla.javascript.NativeJavaObject.reportConversionError(NativeJavaObject.java:863)
 at org.mozilla.javascript.NativeJavaObject.coerceTypeImpl(NativeJavaObject.java:495)
 at org.mozilla.javascript.Context.jsToJava(Context.java:1856)
 at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:142)
 at org.mozilla.javascript.InterfaceAdapter$1.run(InterfaceAdapter.java:83)
 at org.mozilla.javascript.Context.call(Context.java:526)
 at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:509)
 at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:86)
 at org.mozilla.javascript.jdk13.VMBridge_jdk13$1.invoke(VMBridge_jdk13.java:132)
 at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
 at $Proxy12.onLongClick(Unknown Source)
 at android.view.View.performLongClickInternal(View.java:6694)
 at android.view.View.performLongClick(View.java:6652)
 at android.widget.TextView.performLongClick(TextView.java:11346)
 at android.view.View.performLongClick(View.java:6670)
 at android.view.View$CheckForLongPress.run(View.java:25913)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6806)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by hyb1996** [comment]
window.text.longClick(()=>{
    window.setAdjustEnabled(!window.isAdjustEnabled());
    return true;
});
