### ISSUE TITLE
Auto.js (Pro) 停更后的新产品——Pluto.js V8

### ISSUE THREAD

**Issue by hyb1996** [hyb1996/Auto.js#526]
由于众所周知的原因，Auto.js以及Auto.js Pro(内测)已经全部下线并停更。目前，作者已计划推出基于Node.js和V8引擎的Pluto.js V8。**该软件将不包含任何无障碍功能。**
将在这里同步Pluto.js V8的工作。

[x] Node.js 7.9.0移植，支持await/async 
[x] npm 4.0.5移植
[ ] Node.js 8.x移植
[ ] 支持npm install -g (80%，目前大部分模块能正确安装，但是不能正确运行起来）
[ ] Java和JavaScript的交互 (80%)
[ ] 界面调整
[ ] 编写并发布Pluto.js的模块到npm中
    [ ] @plutojs/device
    [ ] @plutojs/ui
    [ ] ...
[ ] 文档、多语言

**Comment by joyoes** [comment]
plutojs根本没有auto.js好用，特别是无障碍，唉！

**Comment by Kleverx** [comment]
这个Pluto.js V8在哪下载？？？？

**Comment by 378978764** [comment]
黑产没办法控制吗？比方说脚本与账号绑定，类似微信小程序的token验证？微信登录才能用，黑产就封微信。

**Comment by cckowin** [comment]
新项目定位是啥啊，如果只是用javascript开发app，不是已经有nativescript,react-native等了吗

**Comment by nmdx** [comment]
是因为有人不遵守协议？  我说怎么鸽了。。

**Comment by CharlesSong** [comment]
好的产品不能因为有人用到坏处就不用了。比如菜刀、汽车、火药等。

**Comment by 564667471** [comment]
真是可惜,人家按键就没事.开源的事就来了.

**Comment by yi-ge** [comment]
太可惜了。可以单拉个有开发能力的组织。

**Comment by wysnxzm** [comment]
工具是双刃剑,不能因噎废食

**Comment by shanlanCoding** [comment]
不支持无障碍后我们能用来做什么，App吗？

**Comment by genspider** [comment]
能不能添加一些对蓝牙的支持，现在穿戴设备都是通过蓝牙来实现交互

**Comment by Curtion** [comment]
是不是和Dorajs类似呀，哈哈🤣

**Comment by RocWangPeng** [comment]
大佬 还在更新pluto嘛，一直在等

**Comment by hujun528** [comment]
不支持无障碍功能建议作者别费时间写了 没人用
 auto.js吸引人的地方也只是无障碍功能，按键精灵、触动精灵之类的都好好的，怎么到你这了，就清高了？ 你这属于自继臂膀

**Comment by cf183838** [comment]
希望大佬可以完善OPENCV剩余功能，方便小白使用OPENCV进行图像识别学习

**Comment by hyb1996** [comment]
> 希望大佬可以完善OPENCV剩余功能，方便小白使用OPENCV进行图像识别学习

OpenCV功能多得是，直接调用即可，不需要我再封装一下

**Comment by cf183838** [comment]
> 大佬还在更新pluto嘛，一直在等

应该是的

**Comment by cf183838** [comment]
> > 希望大佬可以完善OPENCV剩余功能，方便小白使用OPENCV进行图像识别学习
> 
> OpenCV功能多得是，直接调用即可，不需要我再封装一下

好的，那请问是否是以image.xxx的形式调用OPENCV呢?
因为在您的API文档中有写cvtColor等OPENCV函数

**Comment by mao527147880** [comment]
向大佬膜拜\(@^0^@)/

**Comment by freekingg** [comment]
在哪里下载呢

**Comment by hyb1996** [comment]
Pluto.js现已合并到Auto.js Pro。将在Auto.js Pro 8.6中发布。

**Comment by YumikoAzu** [comment]
> Pluto.js现已合并到Auto.js Pro。将在Auto.js Pro 8.6中发布。

你好，请问这个Pluto.js库会开源吗？

**Comment by hyb1996** [comment]
> > Pluto.js现已合并到Auto.js Pro。将在Auto.js Pro 8.6中发布。
> 
> 你好，请问这个Pluto.js库会开源吗？

不会

**Comment by hyb1996** [comment]
> > > 希望大佬可以完善OPENCV剩余功能，方便小白使用OPENCV进行图像识别学习
> > 
> > 
> > OpenCV功能多得是，直接调用即可，不需要我再封装一下
> 
> 好的，那请问是否是以image.xxx的形式调用OPENCV呢?
> 因为在您的API文档中有写cvtColor等OPENCV函数

不是，可以看images模块的源码

**Comment by taozhiyu** [comment]
记得撸码的时候多写方法注释，
看谷歌哪里有问题直接就把函数一跳转然后上面全是注释。。。
而且到时候也方便写api文档

**Comment by fulans1** [comment]
prov9无法安装啊。

**Comment by zzliux** [comment]
> autojs pro v9无法安装,模拟器和真机APK都不行，谁能告诉我怎么安装。

暂不支持

**Comment by fulans1** [comment]
感谢老哥。
本想pro 9 可以直接node.js以使用signalr ，现在看来只能暂时用websocket替代，等出v9再升级，
静候发布V9佳音。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyb1996/Auto.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hyb1996/Auto.js] Auto.js Pro 9.0 Roadmap (带Node.js / V8引擎版本） (#526)





  
autojs pro v9无法安装,模拟器和真机APK都不行，谁能告诉我怎么安装。
  
暂不支持
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hyb1996** [comment]
> > autojs pro v9无法安装,模拟器和真机APK都不行，谁能告诉我怎么安装。
> 
> 暂不支持

已经支持了，需要用64位模拟器。

**Comment by hyb1996** [comment]
因本issue有修改，删除了部分和现有内容不匹配的评论，以免读者困惑。

**Comment by minirain2000** [comment]
@hyb1996 老大，啥时候能把百度文字认别：EasyEdge离线功能也集成到Auto.JS pro里就好了！！

**Comment by hyb1996** [comment]
> @hyb1996 老大，啥时候能把百度文字认别：EasyEdge离线功能也集成到Auto.JS pro里就好了！！

@minirain2000 后面有空会考虑加入的

**Comment by minirain2000** [comment]
> > @hyb1996 老大，啥时候能把百度文字认别：EasyEdge离线功能也集成到Auto.JS pro里就好了！！
> 
> @minirain2000 后面有空会考虑加入的

老大，请教在Auto.js V4.1中可获取控件：let stBobao = className("android.widget.TextView").depth(5).text("点播").findOnce(0).parent().parent().children();
在Auto.jsPro中却始终无法获得该控件？是在新版本中取消该功能了吗？如果在Pro中想获取这样控件内容，该如何写程序呢？急！！

**Comment by ParticleG** [comment]
期待，支持Node以后生态会好很多

**Comment by LiuSuY** [comment]
期待9.0的到来

**Comment by warryy** [comment]
我看v9都有创建的快捷命令了, 以为可以用, 搞了几个小时, 没想到.......

**Comment by ryougifujino** [comment]
V9识图过多会闪退（已经对readImage返回的图进行了recycle）......

**Comment by hyb1996** [comment]
@ryougifujino 是指用nodejs版本的API吗

**Comment by ryougifujino** [comment]
> @ryougifujino 是指用nodejs版本的API吗

是的，使用的是Pro 9.1.16版本，在小米平板5Pro下测试。

```javascript
const path = require('path')
const { readImage, findImage, findImageInRegion } = require('image')
const { requestScreenCapture } = require('media_projection')
const { ASSET_PATH } = require('./constants')

const obtainCapturer = function() {
  let capturer

  return async function() {
    if (!capturer) {
      capturer = await requestScreenCapture()
    }
    return capturer
  }
}()

async function captureScreen() {
  const capturer = await obtainCapturer()
  return await capturer.nextImage()
}

async function getImagePoint(imagePath, screenshot) {
  if (!screenshot) {
    screenshot = await captureScreen()
  }
  const template = await readImage(path.resolve(ASSET_PATH, imagePath))
  const point = await findImage(screenshot, template)
  template.recycle()
  return point
}

async function getImagePointInRagion(imagePath, x, y, width, height, screenshot) {
  if (!screenshot) {
    screenshot = await captureScreen()
  }
  const template = await readImage(path.resolve(ASSET_PATH, imagePath))
  const point = await findImageInRegion(screenshot, template, x, y, width, height)
  template.recycle()
  return point
}

module.exports = {
  getImagePoint,
  getImagePointInRagion,
  captureScreen
}

```
这是具体代码，调用`getImagePoint`次数过多后悬浮窗会突然消失，再去日志看什么也不会看到（只有一个开始记录）。（已经把Auto.js的电池选项和后台改成不杀，并且锁住。）

**Comment by ryougifujino** [comment]
> @ryougifujino 是指用nodejs版本的API吗

还有调用scale方法会报错。
![25875A0331ABEE23DDEA9932B66F9C40](https://user-images.githubusercontent.com/12398033/168471417-2dba2933-215a-40b6-8851-4caa2d5df7c1.jpg)
![242AE522407F1A6E9F9D17C269C11E51](https://user-images.githubusercontent.com/12398033/168471425-689a9a68-ab29-4e57-86af-7ef7f4b015be.jpg)

**Comment by SilurianYang** [comment]
大佬 能加入一些底层的处理吗？比如说hook 比如说api拦截请求之内的。我觉得把这些做到，堪称第一强大

**Comment by LavendaRaphael** [comment]
v9 ui 相关的api和v8差别很大啊，v8的文档完全不适用于v9，v9的文档太简略了，没有简易的样例可以参考

**Comment by txwx** [comment]
V9版本稳定了吗，我现在还在用V8版本

**Comment by Boris-code** [comment]
大佬 几个人开发？大佬是1996年的？

**Comment by hyb1996** [comment]
> > @ryougifujino 是指用nodejs版本的API吗
> 
> 还有调用scale方法会报错。 ![25875A0331ABEE23DDEA9932B66F9C40](https://user-images.githubusercontent.com/12398033/168471417-2dba2933-215a-40b6-8851-4caa2d5df7c1.jpg) ![242AE522407F1A6E9F9D17C269C11E51](https://user-images.githubusercontent.com/12398033/168471425-689a9a68-ab29-4e57-86af-7ef7f4b015be.jpg)

已在内测版修复

**Comment by Bruce-zxy** [comment]
请问为什么9.0的device没有了isScreenOn方法呢？8.0的API的迁移仅仅是迁移了部分的API吗？
![image](https://user-images.githubusercontent.com/22904758/184319539-943425cc-f67e-4c9e-9e88-447e543ad65c.png)

**Comment by hyb1996** [comment]
> 请问为什么9.0的device没有了isScreenOn方法呢？8.0的API的迁移仅仅是迁移了部分的API吗？ ![image](https://user-images.githubusercontent.com/22904758/184319539-943425cc-f67e-4c9e-9e88-447e543ad65c.png)

实现时漏了，下个版本补上。目前用PowerManager.isScreenOn代替

**Comment by springeye** [comment]
麻烦问一下   "内置编辑器优化，支持npm run、运行前编译等交互，基于LSP的智能补全" 进度怎么样了，如果支持这个就可以用webstorm开发了

**Comment by hyb1996** [comment]
> 麻烦问一下 "内置编辑器优化，支持npm run、运行前编译等交互，基于LSP的智能补全" 进度怎么样了，如果支持这个就可以用webstorm开发了

@springeye 这个是手机端的编辑器。PC的话直接安装@autojs/types-pro9 模块

**Comment by SOVLOOKUP** [comment]
vscode 插件用的太蹩脚了，可否出个sdk或者cli，方便开发者把编译命令自动化

**Comment by hyb1996** [comment]
> vscode 插件用的太蹩脚了，可否出个sdk或者cli，方便开发者把编译命令自动化

会在9.2版本优化

**Comment by mission-wuiyu** [comment]
小米平板5 pro 使用版本9会闪退，同是安卓12的k30p 正常，这是啥原因呀？ 谷歌商店里下载的首次启动也是如此，但好像随后又可以了。

**Comment by Fofade** [comment]
- 当我使用Vuejs为主体去开发的时候，我期望直接使用`const app = require("app"); ` 去调用autojs 的模块。
- 但当我如此做的时候，vscode 与AJ pro 9 都在编译时出现了找不到该模块的报错，命令大概是`node node_modules/@vue/cli-service/bin/vue-cli-service.js build`。
- 此时如果我直接打包，可以正常打包，但是安装后的app无法正常打开我需要的页面，会报request error。

报错如下
```js
Error: Build failed with errors.
Error: Build failed with errors.
    at F:\code\free-hands-toolbox\node_modules\@vue\cli-service\lib\commands\build\index.js:207:23
    at F:\code\free-hands-toolbox\node_modules\webpack\lib\webpack.js:148:8
    at F:\code\free-hands-toolbox\node_modules\webpack\lib\HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (F:\code\free-hands-toolbox\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <andeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\code\free-hands-toolbox\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)s:18:14)
    at Cache.shutdown (F:\code\free-hands-toolbox\node_modules\webpack\lib\Cache.js:150:23)
    at F:\code\free-hands-toolbox\node_modules\webpack\lib\Compiler.js:1225:15                                                  deFactory.js:33:10), <an
    at Hook.eval [as callAsync] (eval at create (F:\code\free-hands-toolbox\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)                                                                                           s:18:14)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\code\free-hands-toolbox\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.close (F:\code\free-hands-toolbox\node_modules\webpack\lib\Compiler.js:1218:23)
```


如果我完全不使用AJ的包，那就能正常编译运行，但是我无法使用AJ提供的各种功能。

请问我如何才能在开发Vuejs项目时获得AJ 的能力而不在编译时发生错误？

**Comment by hyb1996** [comment]
> * 当我使用Vuejs为主体去开发的时候，我期望直接使用`const app = require("app"); ` 去调用autojs 的模块。
> * 但当我如此做的时候，vscode 与AJ pro 9 都在编译时出现了找不到该模块的报错，命令大概是`node node_modules/@vue/cli-service/bin/vue-cli-service.js build`。
> * 此时如果我直接打包，可以正常打包，但是安装后的app无法正常打开我需要的页面，会报request error。
> 
> 报错如下
> 
> ```js
> Error: Build failed with errors.
> Error: Build failed with errors.
>     at F:\code\free-hands-toolbox\node_modules\@vue\cli-service\lib\commands\build\index.js:207:23
>     at F:\code\free-hands-toolbox\node_modules\webpack\lib\webpack.js:148:8
>     at F:\code\free-hands-toolbox\node_modules\webpack\lib\HookWebpackError.js:68:3
>     at Hook.eval [as callAsync] (eval at create (F:\code\free-hands-toolbox\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <andeFactory.js:33:10), <anonymous>:6:1)
>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\code\free-hands-toolbox\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)s:18:14)
>     at Cache.shutdown (F:\code\free-hands-toolbox\node_modules\webpack\lib\Cache.js:150:23)
>     at F:\code\free-hands-toolbox\node_modules\webpack\lib\Compiler.js:1225:15                                                  deFactory.js:33:10), <an
>     at Hook.eval [as callAsync] (eval at create (F:\code\free-hands-toolbox\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)                                                                                           s:18:14)
>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (F:\code\free-hands-toolbox\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
>     at Compiler.close (F:\code\free-hands-toolbox\node_modules\webpack\lib\Compiler.js:1218:23)
> ```
> 
> 如果我完全不使用AJ的包，那就能正常编译运行，但是我无法使用AJ提供的各种功能。
> 
> 请问我如何才能在开发Vuejs项目时获得AJ 的能力而不在编译时发生错误？

可以参考下示例的Vue3配置下webpack.config

**Comment by DeadSamurai8** [comment]
> Auto.js Pro 9.0是Auto.js Pro的下一个大版本。其主要更新是支持Node.js和V8引擎，带来了庞大的npm生态，并仍然支持和Android/Java交互（也即可在Node.js中使用Android/Java API）。届时旧的rhino引擎仍然保留，并且旧代码仍然可以直接运行；新的代码建议基于Node.js引擎开发。
> 
> Auto.js Pro 9.0关于Node.js部分的路线图如下：
> 
> # 关键核心功能
> - 引入Node.js引擎和npm
> - V8引擎支持引入Java类，访问Java类字段和方法，实现Java接口、抽象类，线程切换
> - 核心模块API实现
> - 交互式终端，提供运行npm命令和npm -g的cli模块的环境
> - 兼容V8的legacy-apis开发
> - 内置编辑器优化，支持npm run、运行前编译等交互，基于LSP的智能补全
> - 远程调试和本地调试支持
> - 打包支持，支持加密与共享运行时
> 
> 
> # 各部分功能
> 
> > 编辑中
> 
> ## 引擎
> 
> 目前已引入Node.js 16.14。
> - [x] 支持"nodejs"开头的代码自动用nodejs引擎
> - [x] 显示nodejs的错误和输出
> - [x] 提示nodejs的Unhandled Promise Rejection错误
> - [ ] 
> 
> ## Java交互
> 
> - [x] 支持导入Java类，作为构造函数、原型使用
> - [x] 支持构造Java对象，访问成员方法、字段、静态方法、字段
> - [x] 支持对象作为Java接口使用
> - [x] 支持继承Java类（包括抽象类）
> - [ ] 优化Java调用性能
> - [x] 支持Java调用切换线程和Java回调切换线程
> 
> ## 终端
> - [x] 引入termux的Apache协议开源部分，实现终端
> - [x] 解决Android10以上无法运行npm -g的模块的问题
> - [x] 解决react等无法install的问题
> 
> ## 编辑器与打包
> - [ ] 支持运行时自动运行某些编译脚本
> - [x] 支持打包时自动运行某些编译脚本
> - [x] 64位支持VSCode调试
> - [ ] 32位支持VSCode调试
> - [ ] 支持自带编辑器调试
> 
> ## API
> - [x] app
> - [x] console
> - [x] device
> - [x] dialogs
> - [x] engines
> - [x] events
> - [x] floaty
> - [ ] globals
> - [x] images
> - [x] colors
> - [x] keys
> - [x] media
> - [x] plugins
> - [x] power_manager
> - [x] accessibility
> - [x] sensor
> - [x] shell
> - [x] storage
> - [x] settings
> - [x] TimedTask
> - [ ] ui
> - [x] zip
> - [x] RootAutomator
> 
> 未完待续。
> 
> > Pluto.js V8是原计划推出的基于Node.js和V8引擎的脚本软件，现已被废弃，并被合入Auto.js Pro中。以下有的评论为原始Pluto.js的评论内容。
>
