### ISSUE TITLE
在Auto.js Pro V8中如何导入Java类？

### ISSUE THREAD

**Issue by marcong95** [hyb1996/Auto.js#571]
我根据 https://developer.mozilla.org/zh-CN/docs/Mozilla/Projects/Rhino/Scripting_Java 尝试了以下代码

```javascript
console.log(Packages.java.util.ArrayList)

importPackage(Packages.java.util)
console.log(ArrayList)

importClass(Packages.java.util.ArrayList)
console.log(ArrayList)

console.log(Packages.android.os.Parcel)

importPackage(Packages.android.os)
console.log(Parcel)

importClass(Packages.android.os.Parcel)
console.log(Parcel)
```

以空行分隔的每一段代码的输出基本上都是类似于这样子
```
Java class "java.util.ArrayList" has no public instance field or method named "getClass". (file:///android_asset/modules/__util__.js#248)
Java class "java.util.ArrayList" has no public instance field or method named "getClass".
    at formatValue (file:///android_asset/modules/__util__.js:248:0)
    at file:///android_asset/modules/__util__.js:48:0
    at file:///android_asset/modules/__console__.js:18:0
    at [remote]import.js:1:0
```

是ClassPath之类的设置问题吗？我对Java、JavaScript开发都略有涉猎，但是对Android下的开发了解不深，android.os之类的包应该不用设置ClassPath？

此外，我还想确认一下 https://hyb1996.github.io/AutoJs-Docs/ 是最新Pro版本的文档吗？

**Comment by hyb1996** [comment]
console.log会报错是util.format对Java类没支持好。实际上是已经导入了。不过推荐以下用法。
```
let ArrayList = java.util.ArrayList;
let arrayList = new ArrayList();
```

文档的话在doc.autojs.org
