### ISSUE TITLE
将启动app的命令写入一个脚本,然后调用脚本引擎运行该脚本,重复多次,出现该错误

### ISSUE THREAD

**Issue by fxhj3210** [hyb1996/Auto.js#576]
Version: 8000002
Android: 27

Error: java.lang.RuntimeException: Could not read input channel file descriptors from parcel.

java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:37)
	at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:68)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:112)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:110)
	at com.android.internal.view.IInputMethodManager$Stub$Proxy.startInputOrWindowGainedFocus(IInputMethodManager.java:723)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1295)
	at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1543)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3921)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6620)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)

**Comment by hyb1996** [comment]
具体代码呢
