### ISSUE TITLE
悬浮窗spinner 监听click导致autojs闪退

### ISSUE THREAD

**Issue by pansx** [hyb1996/Auto.js#637]
```
    floatyWindow.mainSelect.on('click', (e) => {
        console.log(e);
    });
```
免费版正常,pro会闪退,不清楚怎么回事
还有我想知道在几乎没有文档的情况下如何通过源码了解组件有哪些事件和方法?
[![BzTD56.gif](https://s3.ax1x.com/2020/11/12/BzTD56.gif)](https://imgchr.com/i/BzTD56)

**Comment by pansx** [comment]
新版本此问题没有被修复,顶一下

**Comment by hyb1996** [comment]
使用8.5版本，闪退后会有日志记录

**Comment by pansx** [comment]
2021-01-12 20:13:11.185/TRACE: 开始运行[/storage/emulated/0/脚本/联机重试.js]
2021-01-12 20:13:12.205/ERROR: uncaughtException: thread = Thread[main,5,main]
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:982)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:384)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:101)
	at android.app.Dialog.show(Dialog.java:430)
	at androidx.appcompat.widget.AppCompatSpinner$DialogPopup.show(Unknown Source:53)
	at androidx.appcompat.widget.AppCompatSpinner.showPopup(Unknown Source:10)
	at androidx.appcompat.widget.AppCompatSpinner.performClick(Unknown Source:10)
	at android.view.View$PerformClick.run(View.java:26197)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7002)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by hyb1996** [comment]
悬浮窗应该用不了spinner

**Comment by pansx** [comment]
但是免费版就可以,既然免费版可以pro版应该不可能实现不了
