### ISSUE TITLE
How to import Signature Algorithm to request service? 如何导入自签名证书访问自签名服务网站呢？

### ISSUE THREAD

**Issue by konghehan** [hyb1996/Auto.js#665]
19:44:06.457/E: Wrapped javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. (file:///android_asset/modules/__http__.js#49)
Wrapped javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    at file:///android_asset/modules/__http__.js:49:0
    at /storage/emulated/0/脚本/test1.js:3:0

**Comment by hyb1996** [comment]
使用的版本？我记得Pro中已经支持自签名证书了
