### ISSUE TITLE
Auto.js-Pro-Ext 1.2.4 在 windows 下无法正常处理路径分隔符号

### ISSUE THREAD

**Issue by mslxl** [hyb1996/Auto.js#671]
使用版本:
* Anto.js-Pro-Ext v1.2.4
* AutoJsPro 8.8.5

在 windows 下，如果设定的主脚本的路径不在项目的根目录时，Autojs会试图以包含 windows 路径分隔符的路径运行脚本。

`launch.json` 配置
```json
{
      "type": "autojs",
      "request": "launch",
      "stopOnEntry": true,
      "device": "[recent]",
      "name": "Auto.js Pro Debug",
      "main": "./dist/arkayo.js",
      "preLaunchTask": "webpack: dev"
}
```
调试错误信息:
```trace
java.io.FileNotFoundException: /data/user/0/org.autojs.autojspro/cache/remote_project/2c8c3d43eb804ba6e0f6d435663edee6/dist\arkayo.js (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.stardust.autojs.script.JavaScriptFileSource.֏(:2)
	at com.stardust.autojs.script.JavaScriptSource.Ԫ()
	at okhttp3.internal.io.Ⴆ.ԩ()
	at okhttp3.internal.io.Ⴆ.Ϳ()
	at okhttp3.internal.io.bd0.<init>(:2)
	at okhttp3.internal.io.fe0.Ϳ(:2)
	at okhttp3.internal.io.dd0.Ϳ(:9)
...
```
可以看到`63edee6/dist\arkayo.js`中的`\`十分突兀

已经确认在 `/data/user/0/org.autojs.autojspro/cache/remote_project/2c8c3d43eb804ba6e0f6d435663edee6/dist/arkayo.js` 文件确实存在，但无法通过vsc插件运行，个人推测是 android 无法识别vsc传送的包含 windows 的路径分隔符的参数。

仅在windows上进行了测试，不确定在 linux 下是否有相同现象

**Comment by hyb1996** [comment]
在Pro 8.8.7中已经修复，请等待上线或者加入内测

**Comment by hyb1996** [comment]
如果新版本仍然有问题，可以重新open
