### ISSUE TITLE
Root指令 无法在安卓虚拟机上运行

### ISSUE THREAD

**Issue by ashesofdream** [hyb1996/Auto.js#685]
代码：
`
var Ra = new RootAutomator();
events.on("exit",function(){Ra.exit();})
sleep(1000)
Ra.tap(500,500)
sleep(2000)
exit()
`
运行环境：x8沙箱、VMOS
VSCode远程调试，报错提示：

`
-------VMos
Script-1 Main [remote://~~~/main.js]/E: Wrapped com.stardust.autojs.core.inputevent.RootAutomator$RootAutomatorException: RootAutomator exit with code '2': could not open /dev/input/event3, Permission denied
cannot open device: qwerty2
    at RootAutomator (file:///android_asset/modules/__RootAutomator__.js:9:0)
    at /data/user/0/org.autojs.autojspro/cache/remote_project/~~~/main.js:1:0
`
`
------x8沙箱
[/data/data/org.autojs.autojspro/cache/remote_project//~~~/main.js]运行结束，用时0.228000秒 
06-30 01:28:39.749 Script-1 Main [remote:///~~~/main.js]/E: Wrapped com.stardust.autojs.core.inputevent.RootAutomator$RootAutomatorException: RootAutomator exit with code '2': WARNING: linker: /data/app/org.autojs.autojspro-2/lib/arm/libroot_automator.so: unused DT entry: type 0x6ffffffe arg 0x82c
WARNING: linker: /data/app/org.autojs.autojspro-2/lib/arm/libroot_automator.so: unused DT entry: type 0x6fffffff arg 0x1
could not open /dev/input/event3, Permission denied
cannot open device: dev_touch
    at RootAutomator (file:///android_asset/modules/__RootAutomator__.js:9:0)
    at /data/data/org.autojs.autojspro/cache/remote_project//~~~/main.js:1:0
`
版本：8.8.13-0Pro版

**Comment by hyb1996** [comment]
报错信息是一个permission denied，也就是无权限。
尝试用termux/adb运行getevent或者sendevent看是否有权限？

**Comment by ashesofdream** [comment]
> 报错信息是一个permission denied，也就是无权限。
> 尝试用termux/adb运行getevent或者sendevent看是否有权限？

![Uploading IMG_20210630_161156.jpg…]()

**Comment by ashesofdream** [comment]
> 报错信息是一个permission denied，也就是无权限。
> 尝试用termux/adb运行getevent或者sendevent看是否有权限？

![IMG_20210630_161156](https://user-images.githubusercontent.com/53961395/123926473-7c752e00-d9be-11eb-98d6-4f34b2682e25.jpg)

**Comment by hyb1996** [comment]
看起来就是没有权限。执行一下`chmod 777 /dev/input/event3'试试。

**Comment by ashesofdream** [comment]
> 看起来就是没有权限。执行一下`chmod 777 /dev/input/event3'试试。

![Screenshot_2021-06-30-17-42-34-701_com vmos pro](https://user-images.githubusercontent.com/53961395/123939379-aa606f80-d9ca-11eb-9a5d-5c662ce87446.jpg)

**Comment by ashesofdream** [comment]
> 看起来就是没有权限。执行一下`chmod 777 /dev/input/event3'试试。

之前一直用的按键精灵 root使用是没啥问题的...

**Comment by fenghengzhi** [comment]
我这边测下来也是vmos上的安卓7无法运行root点击，无障碍点击没问题，vmos上的安卓5无障碍点击和root点击都用不了
