### ISSUE TITLE
startActivity extras 值不能为 object

### ISSUE THREAD

**Issue by rvluxx** [hyb1996/Auto.js#699]
```
app.startActivity({
    root: true,
    flags: ['ACTIVITY_NEW_TASK'],
    packageName: 'com.xxxxxxx',
    className: 'com.xxxxxxx.activity.react.xxxxxxx',
    extras: {
        'businessId': 'xxxxxxx',
        'BundleLaucher': {'codeType': '01'}
    }
})
```

报错内容：
```
TypeError: unknown type: [object Object]
    at typeChar (file:///android_asset/modules/__app__.js:178:0)
    at file:///android_asset/modules/__app__.js:209:0
    at file:///android_asset/modules/__app__.js:71:0
    at remote://unionpay.js:1:0
```

**Comment by SuperMonster003** [comment]
因为 extras 属性值不支持传入 JavaScript Object
可尝试传入一个 Bundle

```js
app.startActivity({
    root: true,
    flags: ['ACTIVITY_NEW_TASK'],
    packageName: 'com.xxxxxxx',
    className: 'com.xxxxxxx.activity.react.xxxxxxx',
    extras: {
        'businessId': 'xxxxxxx',
        'BundleLaucher': function getBundle$iiFe() {
            let bundle = new android.os.Bundle();
            bundle.putString('codeType', '01');
            return bundle;
        }(),
    },
});
```

参阅:
https://developer.android.com/reference/android/content/Intent#putExtras(android.os.Bundle)
https://developer.android.com/reference/android/os/Bundle

**Comment by rvluxx** [comment]
E: TypeError: unknown type: Bundle
也不支持Bundle类型。

**Comment by SuperMonster003** [comment]
root是true 会用adb shell 而不是context的startActivity 不支持复杂类型 shell 是支持字符串的 所以可以考虑将对象串化 就像图像可以串化成 data: 开头的字串一样 一般就是 json 或者 base64 可以试试看

**Comment by rvluxx** [comment]
我目的是拉起一个app里的exported=false的活动，只能用root了，但这个活动使用的结构是Bundle里面又包含一个值为Bundle的参数。adb shell 我看下下文档 也只支持一些基础类型，那就没有办法了嘛

**Comment by hyb1996** [comment]
提供一个思路: shizuku。

**Comment by rvluxx** [comment]
> 提供一个思路: shizuku。

可以说下原理吗？刚才看了半天shikuzu官网介绍还是不理解要怎么做到我的目的。
