### ISSUE TITLE
vscode插件生成v9模板项目无法运行

### ISSUE THREAD

**Issue by qiuzongyuan** [hyb1996/Auto.js#723]
使用 Auto.js-Pro-Ext 生成 V9 项目，连接设备，运行项目报错

```
Main [remote://4f3f64fb852c1127e4d97ff872b21061/main.js]/E: Error: Module "/data/user/0/org.autojs.autojspro/cache/remote_project/4f3f64fb852c1127e4d97ff872b21061/toast" not found.
    at Require (file:///android_asset/modules/jvm-npm.js:96:0)
    at /data/user/0/org.autojs.autojspro/cache/remote_project/4f3f64fb852c1127e4d97ff872b21061/main.js:3:0
```

**Comment by qiuzongyuan** [comment]
已解决
